components:
  schemas:
    AggregateRating:
      description: https://www.schema.org/AggregateRating
      properties:
        bestRating:
          type: number
        id:
          format: int64
          type: integer
        ratingCount:
          type: number
        ratingValue:
          type: number
        self:
          format: uri
          type: string
        worstRating:
          type: number
      type: object
    Comment:
      description: https://www.schema.org/Comment
      properties:
        comments:
          $ref: "#/components/schemas/Comment"
        creator:
          format: uri
          type: string
        id:
          format: int64
          type: integer
        self:
          format: uri
          type: string
        text:
          type: string
      type: object
    ContentDocument:
      description: https://www.schema.org/ContentDocument
      properties:
        contentUrl:
          type: string
        creator:
          format: uri
          type: string
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        encodingFormat:
          type: string
        fileExtension:
          type: string
        id:
          format: int64
          type: integer
        self:
          format: uri
          type: string
        sizeInBytes:
          type: number
        title:
          type: string
      type: object
    ContentStructure:
      description: https://www.schema.org/ContentStructure
      properties:
        availableLanguages:
          items:
            type: string
          type: array
        contentSpace:
          format: uri
          type: string
        creator:
          format: uri
          type: string
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        self:
          format: uri
          type: string
      type: object
    StructuredContent:
      description: https://www.schema.org/StructuredContent
      properties:
        aggregateRating:
          $ref: "#/components/schemas/AggregateRating"
        availableLanguages:
          items:
            type: string
          type: array
        category:
          format: uri
          type: string
        comment:
          $ref: "#/components/schemas/Comment"
        contentSpace:
          format: uri
          type: string
        contentStructure:
          $ref: "#/components/schemas/ContentStructure"
        creator:
          format: uri
          type: string
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        datePublished:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        keywords:
          items:
            type: string
          type: array
        lastReviewed:
          type: string
        renderedContentsByTemplate:
          description: https://www.schema.org/templates
          properties:
            id:
              format: int64
              type: integer
            renderedContent:
              type: string
            self:
              format: uri
              type: string
            template:
              type: string
          type: object
        self:
          format: uri
          type: string
        title:
          type: string
        values:
          description: https://www.schema.org/ContentFieldValue
          properties:
            dataType:
              type: string
            document:
              $ref: "#/components/schemas/ContentDocument"
            filterAndSortIdentifier:
              type: string
            geo:
              description: https://www.schema.org/GeoCoordinates
              properties:
                id:
                  format: int64
                  type: integer
                latitude:
                  type: number
                longitude:
                  type: number
                self:
                  format: uri
                  type: string
              type: object
            id:
              format: int64
              type: integer
            inputControl:
              type: string
            label:
              type: string
            link:
              type: string
            name:
              type: string
            self:
              format: uri
              type: string
            structuredContent:
              $ref: "#/components/schemas/StructuredContent"
            value:
              type: string
          type: object
      type: object
info:
  description: ""
  title: ""
  version: 1.0.0
openapi: 3.0.1
paths:
  "/aggregate-rating/{id}":
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AggregateRating"
          description: ""
  "/comment/{id}":
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
          description: ""
  "/comment/{parent-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
  "/content-document/{id}":
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentDocument"
          description: ""
  "/content-space/{parent-id}/content-structures":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ContentStructure"
                type: array
          description: ""
  "/content-space/{parent-id}/structured-contents":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/StructuredContent"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/content-space/{parent-id}/structured-contents/batch-create":
    post:
      parameters:
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/content-structures/{id}":
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentStructure"
          description: ""
  "/content-document/{parent-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
  "/structured-contents/{id}":
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
  "/structured-contents/{parent-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""